apiVersion : apps/v1
kind: Deployment
metadata:
  name: "dnazureaks-91d8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "dnazureaks-91d8"
  template:
    metadata:
      labels:
        app: "dnazureaks-91d8"
    spec:
      containers:
        - name: "dnazureaks-91d8"
          image: "orderitem.azurecr.io/dnazureaks"
          ports:
          - containerPort: 80